### ISSUE TITLE
在 Pod 内增加集群信息

### ISSUE THREAD

**Issue by sailxjx** [opendilab/DI-orchestrator#16]
希望以 dijob replica 方式提交时，每个 pod 都能见到整个 replica 的 host 信息和自己的启动顺序，增加以下几个环境变量：

1. replica 中所有 pod 的 FQDN，依据启动顺序排序
2. 当前 pod 的 FQDN
3. 当前 pod 的顺序编号

DI-engine 中会根据这些变量实现对应的网络连接，attach-to 的生成逻辑可以从 di-orchestrator 中移除

**Comment by konnase** [comment]
那现在通过ditask提交任务的命令是什么？

**Comment by sailxjx** [comment]
`ditask --package $BASEDIR/../entry --main main_league.main --platform k8s` 增加一个 platform，其他参数都照单机版本配置就行了，di-engine 里面做适配。例如 --n-workers=2，同时又两个 pod，就会自动分配到两个 pod 上，每个 pod 一个 worker。

**Comment by konnase** [comment]
done
