### ISSUE TITLE
allocate的一些问题

### ISSUE THREAD

**Issue by RZ-Q** [opendilab/DI-orchestrator#29]
1.目前的allocator的逻辑，对于不可被抢占的job的初始分配，仅利用minreplicas修改replicas属性，那job的pods部署到哪个节点是完全由K8S决定吗？而且Release1.13代码的allocator.go中对不可被抢占job的初始分配部分貌似还没有写。
2.job是否可以被抢占的含义具体是什么？和是否能被调度是不是等价的？
3.调度策略的FitPolicy的Allocate和Optimize方法也没有进行实现，这部分内容什么时候可以补充？
4.文档中存在许多与最新代码不符合的地方，比如DIJob.Spec.Group属性在代码中已经被移除，文档中提到的job.spec.minreplicas属性代码中也没有，而是在JobInfo中。可以更新一下文档吗？
感谢！

**Comment by konnase** [comment]
1. 目前 allocator 还没有实现分配的能力，还是看用户自己定义起多少个 pod。
2. job 是否可被抢占的定义是该 job 是否交给 allocator 做自动化调度，包括增减 pod，调度到不同节点。不过目前 allocator 不具备这个能力。
3. 这部分短期内不会补充，看是否有感兴趣的同学想参与这一块可以一起讨论方案。
4. 文档近期我们会再更新一份。

感谢提出的宝贵建议，我们会持续完善！

**Comment by RZ-Q** [comment]
感谢回答！

**Comment by konnase** [comment]
> 您好，我是一个在校学生，最近在学习kubebuilder，请问下有没有一些现有的有类似allocator功能的自定义调度器的开源代码或者文档，想学习学习( •̥ ω •̥ 人)。因为感觉您写的orchestrator非常好，能从里面学到不少东西。

可以看看 adaptdl 的代码：https://github.com/petuum/adaptdl
